apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      run: myapp
  replicas: 1
  template:
    metadata:
      labels:
        run: myapp
    spec:
      containers:
      - name: my-app
        image: senlinzhan/my-app:v0.1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  labels:
    run: myapp
spec:
  ports:
  - port: 8877
    targetPort: 5000
    protocol: TCP
  selector:
    run: myapp