apiVersion: v1
kind: Namespace
metadata:
  name: sidecar-system
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sidecars.yisaer.github.io
  namespace: sidecar-system
spec:
  group: yisaer.github.io
  version: v1alpha1
  names:
    kind: Sidecar
    plural: sidecars
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            containers:
              description: 'containers contains two pieces of information: 1. normal
                container info that should be injected into pod 2. custom fields to
                control insert behavior(currently empty)'
              items:
                type: object
              type: array
            selector:
              description: selector is a label query over pods that should be injected
              type: object
          type: object
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sidecar-inject-manager
  namespace: sidecar-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sidecar-inject-manager-role
  namespace: sidecar-system
rules:
  - apiGroups:
      - yisaer.github.io
    resources:
      - sidecars
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sidecar-inject-manager-rolebinding
  namespace: sidecar-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sidecar-inject-manager-role
subjects:
  - kind: ServiceAccount
    name: sidecar-inject-manager
    namespace: sidecar-system
---
apiVersion: v1
data:
  cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR1ekNDQXFPZ0F3SUJBZ0lVZUZ5YU0wc253aVVBYnVkNWZBNUkva1JBVEhBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZURVRNQkVHQTFVRUF4TUthM1ZpWlhKdVpYUmxjekFlRncweE9UQTNNVE13TmpJNE1EQmFGdzB5TURBMwpNVEl3TmpJNE1EQmFNRG94T0RBMkJnTlZCQU1UTDNOcFpHVmpZWEl0YVc1cVpXTjBiM0l0ZDJWaWFHOXZheTF6CmRtTXVjMmxrWldOaGNpMXplWE4wWlcwdWMzWmpNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUIKQ2dLQ0FRRUErT3h2K2VlTHZvRzZFOFhXeEVJbGJ4QjBTOTNHYWtqaEVWbEp4YWxCMEpQUGpxYStFSmUxOGwzeApwekJnVlRScTVKNHBEOVNBdml2UHhrZEhDdlhSanQ3VVVUeGlyeFROVXVabURub1R3d0EwdHo2VEFQM1B3TzhJCjFGblQyZTI2RE4ybU8rbGpTL0FibzdkNWVWT04xRkRIRmM3VU9lNzZqUnhPZmJMK3cyRXQ0c1BLdEtUaUVPdysKdjI2R1RzSUU0bzAzN2RSS2lTZjBiVGhaUFZNbHdlTXhUcmZoYWU5ZnNFUE9mYURWY3dLWTBFSVVqUTBKS2NBUQo1ZDBTbHhXU2trQmxVQksyR1RQRDRsWlpQaDBqZ1Zmbm56ZGdxcVpDWElRMUFqaXduL25WNmVNSHFGc3ZjY2ppCmp1MnUyWkVMMzM3VzNjME1GYUtSSmhacVkrcjhhd0lEQVFBQm80SGRNSUhhTUE0R0ExVWREd0VCL3dRRUF3SUYKb0RBVEJnTlZIU1VFRERBS0JnZ3JCZ0VGQlFjREFUQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJRagpXWUlKMy9DakJRYTAzZFQzVngxdUJVMUp6akNCaFFZRFZSMFJCSDR3ZklJY2MybGtaV05oY2kxcGJtcGxZM1J2CmNpMTNaV0pvYjI5ckxYTjJZNElyYzJsa1pXTmhjaTFwYm1wbFkzUnZjaTEzWldKb2IyOXJMWE4yWXk1emFXUmwKWTJGeUxYTjVjM1JsYllJdmMybGtaV05oY2kxcGJtcGxZM1J2Y2kxM1pXSm9iMjlyTFhOMll5NXphV1JsWTJGeQpMWE41YzNSbGJTNXpkbU13RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUVFVVRLVWIwUDljTkZINXc2NUNhOUd3ClNBcUJrbTBmcVpPbUtESFBoS2pWZDExVW0zQnlBN3orTHRZQmdpYlRtTjJBaHdsWm51aSt6S3hNWjJJRmI1eWcKaGJHN2Z2UjZ1OVA0eWZHZi80eDJSYmxXRy83a0owbjVkK0lhc0kwclkvU3pIcmo0MHhkTEthRHdsYVd6WkNWdgpwTE0wbHFtTytOWkxVNkxnMFhLVHlzOHdjS2RqZitlVEZmUGcwbVhFaHcvQmViK2g1QVI4dXZEbGZETEpzZVJKCisxR3dCdnNrSXBQQW91VjM2ZkRSeUVxMDFxOEdWQlhxUlYrYUU3azhZMzZ2TmNtcEQvQk5NTTdoWkF0ZlYyUVUKbnRGOU10cEQzejFzcWZqVldNVFdXdC94V2c3bW1rM0R6enU0dlgvQzlMWHVFUjBwbGE2emZQWUg0ejBhM1JvPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  key.pem: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBK094ditlZUx2b0c2RThYV3hFSWxieEIwUzkzR2FramhFVmxKeGFsQjBKUFBqcWErCkVKZTE4bDN4cHpCZ1ZUUnE1SjRwRDlTQXZpdlB4a2RIQ3ZYUmp0N1VVVHhpcnhUTlV1Wm1Ebm9Ud3dBMHR6NlQKQVAzUHdPOEkxRm5UMmUyNkROMm1PK2xqUy9BYm83ZDVlVk9OMUZESEZjN1VPZTc2alJ4T2ZiTCt3MkV0NHNQSwp0S1RpRU93K3YyNkdUc0lFNG8wMzdkUktpU2YwYlRoWlBWTWx3ZU14VHJmaGFlOWZzRVBPZmFEVmN3S1kwRUlVCmpRMEpLY0FRNWQwU2x4V1Nra0JsVUJLMkdUUEQ0bFpaUGgwamdWZm5uemRncXFaQ1hJUTFBaml3bi9uVjZlTUgKcUZzdmNjamlqdTJ1MlpFTDMzN1czYzBNRmFLUkpoWnFZK3I4YXdJREFRQUJBb0lCQUc4RG8zemtreUpIWU9GbwpuanV3OUZqd0VhMjBIc1ZQODNCMVRiMWxtd0NXcXo2SGhzU0hwSkdPN0RNUUZDWnIxakJYaVNDU09VaVc2WGNZCldzcThqdFVVODhPM0Zwdld2eXQxclpaUFEzajRJb3FHMGJEamdVQWVXdVc1bWczYlE5cHhENjR3akNSVjFUM1MKbWM1T1FUYXJQOTZ0KzJCTEFGcm1nT3IyWlVCa3VZOXlQQm5hVGhoR2YrbUVNVnE3Qi93K01HeWFJRzN0QUlFdwpITWhacTloc3FMYXN5MXFENFhaNTYzc28wcFI2UWxyZGIrcml1YnV4SHQrckdtQm9EcG0zSGRJVWcrelVVdllrCnE2WXF1RmVhb3ZWL1FHTFNNK0Q5c0NmMG4rcHFhUm9kcXBxVy8waGQydmJWOEd0Ni9NZVBxSFdYdzN5aUgvLzEKT0hzWjZHRUNnWUVBLzRqSHNDdEpaandhZDNJMWZOY3gzNmNhaHRGWU5EYkhSTmdidmxiMitUQmtkMXA3MTJtQgpJTlVYbjRVRDNNcm5wMlhUcWpsQ1AwV3JhaTVQcGNEYVNQK3VVRzhrZlVsdjlhZnVHVm12YVo3NnowU2xNcHRYCkF1bHBuTGN6MVJGcGtFMS8wK1RmeU90RmNkdTlFRFoweEt0RmRvOGlJMEhqZ0JCMm5hZDJUWGNDZ1lFQStXQ1MKdVArbUxiZEhvbC91TmxzdWNjRTZMTG1ZQ1RmZzlsNXF0elE0bktsaWFJRDAzWXhtMm5Ya1lUeWMvYm12ZDFnbApHUlFjVHpac04weVMxbSt5dXVVWkNrQ3BGSnZYU1d5ZGpwZEMwa2gvMDhvUlZ4RklyRFI3bUxMMTd4UnBXalR3CnM2eDhNSnpBS1Z6a0hDZWVIWDE2YjVKUmE3L0RLUWUwWlh4Sk5hMENnWUFYVWdkUFY1UDZSWS93eUxhQzd5eTUKQ1lvTk5idkVBQi9OYzUrTWptazVzcVhva3BSc3cwOHFqT2Y4QWVxcFVzY3phc0tYYldSVFcrdFo1R0lXY1hRNgpaME1rU2hCZGNyOUovd3BtdTkyYldRdndzSVlYQ1VBMm50Q3BvYnFVUG1PUTdORzJwOU9ZaFlndjdPcmpPT1VOCk1jaEVHcW4xNThSNFlvaEF1UkM5M3dLQmdRQzNzRzBqSEJ5Nk8vRG1LQ2Q5bm5oOWprbGR2Ry9EQ29nSXNjK0YKbDAvRUJmalk1WFI0NVB5MkduVFpNeDZvdm1nRFRzZzB5dDEzYzYwT3ByYmFnWGh6dG1GVmJmK2RrSlZxSGptSQpXTjc5cWkyT1FaKzROS0VGUjd0cTVSZkd2WkJFeEE0eEt2Sm5sRzd2aU43MTVqRFBwQ2ZWbXoraVVLUmV5ckFVCnVSSHNHUUtCZ0ZicTVWd0ZDc29JMEgrd2VHY0wrTWNxb2ZSS0svY3U4MWZWc3pBOENKdFFIVU5LRGZiR2hEWGQKY3VWUFhoRWIxNFIzM3IzY1daZ2pjclk0NmRiOXJDbGVqc0d0WnpkVURPSVplb21Ua3hXeEV3eHhIL2krdlJWTQpYWWl3ODJHdGprMkRKMkU3NSt4R1JGT0hzOFBtRWhpSUovWlRwaC93RkU4VXZ5azNHQUNvCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  name: sidecar-injector-webhook-certs
  namespace: sidecar-system
type: Opaque

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sidecar-injector-webhook-deployment
  namespace: sidecar-system
  labels:
    app: sidecar-injector
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sidecar-injector
    spec:
      serviceAccount: sidecar-inject-manager
      containers:
        - name: sidecar-injector
          image: yisaer/sidecar-inject-server:v1
          imagePullPolicy: IfNotPresent
          args:
            - -ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            - -authToken=/var/run/secrets/kubernetes.io/serviceaccount/token
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: sidecar-injector-webhook-certs
---
apiVersion: v1
kind: Service
metadata:
  name: sidecar-injector-webhook-svc
  namespace: sidecar-system
  labels:
    app: sidecar-injector
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: sidecar-injector
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: sidecar-injector-webhook-cfg
  namespace: sidecar-system
  labels:
    app: sidecar-injector
webhooks:
  - name: sidecar-injector.morven.me
    clientConfig:
      service:
        name: sidecar-injector-webhook-svc
        namespace: sidecar-system
        path: "/mutate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR1ekNDQXFPZ0F3SUJBZ0lVZUZ5YU0wc253aVVBYnVkNWZBNUkva1JBVEhBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZURVRNQkVHQTFVRUF4TUthM1ZpWlhKdVpYUmxjekFlRncweE9UQTNNVE13TmpJNE1EQmFGdzB5TURBMwpNVEl3TmpJNE1EQmFNRG94T0RBMkJnTlZCQU1UTDNOcFpHVmpZWEl0YVc1cVpXTjBiM0l0ZDJWaWFHOXZheTF6CmRtTXVjMmxrWldOaGNpMXplWE4wWlcwdWMzWmpNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUIKQ2dLQ0FRRUErT3h2K2VlTHZvRzZFOFhXeEVJbGJ4QjBTOTNHYWtqaEVWbEp4YWxCMEpQUGpxYStFSmUxOGwzeApwekJnVlRScTVKNHBEOVNBdml2UHhrZEhDdlhSanQ3VVVUeGlyeFROVXVabURub1R3d0EwdHo2VEFQM1B3TzhJCjFGblQyZTI2RE4ybU8rbGpTL0FibzdkNWVWT04xRkRIRmM3VU9lNzZqUnhPZmJMK3cyRXQ0c1BLdEtUaUVPdysKdjI2R1RzSUU0bzAzN2RSS2lTZjBiVGhaUFZNbHdlTXhUcmZoYWU5ZnNFUE9mYURWY3dLWTBFSVVqUTBKS2NBUQo1ZDBTbHhXU2trQmxVQksyR1RQRDRsWlpQaDBqZ1Zmbm56ZGdxcVpDWElRMUFqaXduL25WNmVNSHFGc3ZjY2ppCmp1MnUyWkVMMzM3VzNjME1GYUtSSmhacVkrcjhhd0lEQVFBQm80SGRNSUhhTUE0R0ExVWREd0VCL3dRRUF3SUYKb0RBVEJnTlZIU1VFRERBS0JnZ3JCZ0VGQlFjREFUQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJRagpXWUlKMy9DakJRYTAzZFQzVngxdUJVMUp6akNCaFFZRFZSMFJCSDR3ZklJY2MybGtaV05oY2kxcGJtcGxZM1J2CmNpMTNaV0pvYjI5ckxYTjJZNElyYzJsa1pXTmhjaTFwYm1wbFkzUnZjaTEzWldKb2IyOXJMWE4yWXk1emFXUmwKWTJGeUxYTjVjM1JsYllJdmMybGtaV05oY2kxcGJtcGxZM1J2Y2kxM1pXSm9iMjlyTFhOMll5NXphV1JsWTJGeQpMWE41YzNSbGJTNXpkbU13RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUVFVVRLVWIwUDljTkZINXc2NUNhOUd3ClNBcUJrbTBmcVpPbUtESFBoS2pWZDExVW0zQnlBN3orTHRZQmdpYlRtTjJBaHdsWm51aSt6S3hNWjJJRmI1eWcKaGJHN2Z2UjZ1OVA0eWZHZi80eDJSYmxXRy83a0owbjVkK0lhc0kwclkvU3pIcmo0MHhkTEthRHdsYVd6WkNWdgpwTE0wbHFtTytOWkxVNkxnMFhLVHlzOHdjS2RqZitlVEZmUGcwbVhFaHcvQmViK2g1QVI4dXZEbGZETEpzZVJKCisxR3dCdnNrSXBQQW91VjM2ZkRSeUVxMDFxOEdWQlhxUlYrYUU3azhZMzZ2TmNtcEQvQk5NTTdoWkF0ZlYyUVUKbnRGOU10cEQzejFzcWZqVldNVFdXdC94V2c3bW1rM0R6enU0dlgvQzlMWHVFUjBwbGE2emZQWUg0ejBhM1JvPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        sidecar-injector: enabled