apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sidecars.yisaer.github.io
  labels:
    app: {{ template "sidecar-inject-init.name" . }}
    chart: {{ template "sidecar-inject-init.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  group: yisaer.github.io
  version: v1alpha1
  names:
    kind: Sidecar
    plural: sidecars
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            containers:
              description: 'containers contains two pieces of information: 1. normal
                container info that should be injected into pod 2. custom fields to
                control insert behavior(currently empty)'
              items:
                type: object
              type: array
            selector:
              description: selector is a label query over pods that should be injected
              type: object
          type: object