apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: sidecar-injector-webhook-cfg
  labels:
    app: {{ template "sidecar-inject-server.name" . }}
    chart: {{ template "sidecar-inject-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
webhooks:
  - name: sidecar-injector.yisaer.github.io
    clientConfig:
      service:
        name: sidecar-injector-webhook-svc
        namespace: {{ .Release.Namespace }}
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01EY3lNakEyTXpNeU5Gb1hEVE13TURjeU1EQTJNek15TkZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS3VkCmVSWG5wWW5IY0F2b2lqTkFXL2JxaUErYjFpaWR3djJNWFVhbzZIYVptMDhManRHVjFTL2NQSG1WbDVVUkVKYTgKb05qYk9NdWtGUThuTG5iS1BoSlR6c0wwQlBzdDZ3VmJhcGdaOHpueGVGbVVkVEkrVDRvN0xJejRwdWxrNW1ibgpvdUZEOWZXOVVwSjcyYXQ3TjZTQURWNUl6dGtNT01IbHVhSk54aHQzbUtlVmM2VE8vQW40THg3VnUyMDBsZFllClVtQ0FhbzVGNncrNU10clRoYU8vOUpsWXppTGZ5MEE0QVRQalRvd0wyajdETlB3NVRncWg0alJKZDZjRDJMMWYKNXNDMFdDajFQUEZwbVkvbXlFNFR1OXA3M2NoNTBOM2pPV2gvYm9vU3JZckJuejhJZnRQMHBpNWNPRk1ydHJiQQo5YVBBVU53by9paHFydURQK3hzQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFCajVhZzhYcHpLdEpQZVVUL21EMElxWGpGMG4KMksySUFYK1d5SHFKdmJ2dXlZYWp5bHdhc2U3OFJqZmp2NXBDeTBKNTBhSzJtSzlac1ZxUFgxN29VRnJqOVFsRApLcnNJOXdBSTBGRldidVFKaWxnSGEzOTdjWVcyS0RNUm9oL3J1VHAvUjJtcHQ2RVFDUDkyblFYMmo5RCtxWlNFCkdmYmZFQ3BFMmFGSVlwbzNXZXh3cFNrM3lZV3hQaVp5VmFUbngvZmg5Vmp0Qk1hNzVrZHFUU1NBYUV2ZlVUY1gKL05LdXdrdjBITFdyRno4amFlZmRIQlcxeDlxd0ZUMTlMK2ozSDltRjlNOFhhQWhDaDd2NFRLRkRVbDZXekk1cApXSXhKZHZZOGZORFArWFYxRWthMkE4dk5kNytzckZMdjBBaDBoMUVUR2FZVkY2cVJCVTF2NWJYU2tqdz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        sidecar-injector: enabled