---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sidecar-inject-manager
  labels:
    app: {{ template "sidecar-inject-server.name" . }}
    chart: {{ template "sidecar-inject-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}